name: davidgusmao
favicon: null
layout_spectrum: 0.8956406249199063
typography_spectrum: 0.23746311431750655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6010887362062931
  lightness: 0.43348868610337377
  saturation: 0.9348707215394825
  rhythmicContrast: 0.6491882449481636
purpose: []
